linters-settings:
  govet:
    enable:
      - shadow  # Включаем проверку shadow вместо check-shadowing
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: hexlet-boilerplates/gopackage

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gofmt
    - goimports
    - bodyclose
    - unconvert
    - prealloc

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0